name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-skip:
    name: ✋🏼 Cancel Previous Redundant Builds
    runs-on: ubuntu-latest
    steps:
      - name: ✋🏼 Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  assign_pr_owner:
    runs-on: ubuntu-latest
    name: 📝 Assign PR to creator
    steps:
      - name: 📝 Assign PR to creator
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    name: 💅🏼 Linting
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 💅🏼 Linting
        run: npm run lint
  testing:
    runs-on: ubuntu-latest
    name: ✅ Testing
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ✅ Testing
        run: npm run test
  build:
    runs-on: ubuntu-latest
    name: 👷🏻‍♀️ Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: 👷🏻‍♀️ Build dependencies
        run: npm run build
