name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: 🚀 Pipeline
    timeout-minutes: 15

    steps:
      - name: ✋🏼 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: 👍 Checkout
        uses: actions/checkout@v2

      - name: 📥 Install Dependencies
        run: npm install --no-audit --no-fund --omit=optional

      - name: 💅 Lint
        run: npm run lint

      - name: 👷🏻‍♀️ Build
        run: npm run build

      - name: ✅ Unit tests
        run: npm run test
